In [4]:
pip install nba_api

Collecting nba_api
  Downloading nba_api-1.1.14-py3-none-any.whl (254 kB)
Requirement already satisfied: requests in c:\users\gregp\anaconda3\lib\site-packages (from nba_api) (2.25.1)
Collecting numpy<2.0.0,>=1.22.2
  Downloading numpy-1.24.2-cp38-cp38-win_amd64.whl (14.9 MB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gregp\anaconda3\lib\site-packages (from requests->nba_api) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\gregp\anaconda3\lib\site-packages (from requests->nba_api) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\gregp\anaconda3\lib\site-packages (from requests->nba_api) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\gregp\anaconda3\lib\site-packages (from requests->nba_api) (4.0.0)
Installing collected packages: numpy, nba-api
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
Successfully installed nba-api-1.1.14 numpy-1.24.2
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.6.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.2 which is incompatible.

In [5]:
#Lets grab some player data

In [6]:
from nba_api.stats.endpoints import playercareerstats

# Nikola Jokić
career = playercareerstats.PlayerCareerStats(player_id='203999') 

# pandas data frames (optional: pip install pandas)
career.get_data_frames()[0]

# json
career.get_json()

# dictionary
career.get_dict()

{'resource': 'playercareerstats',
 'parameters': {'PerMode': 'Totals', 'PlayerID': 203999, 'LeagueID': None},
 'resultSets': [{'name': 'SeasonTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2015-16',
     '00',
     1610612743,
     'DEN',
     21.0,
     80,
     55,
     1733.0,
     307,
     600,
     0.512,
     28,
     84,
     0.333,
     154,
     190,
     0.811,
     181,
     379,
     560,
     189,
     79,
     50,
     104,
     208,
     796],
    [203999,
     '2016-17',
     '00',
     1610612743,
     'DEN',
     22.0,
     73,
     59,
     2038.0,
     494,
     854,
     0.578,
     45,
     139,
     0.324,
     188,
     228,
     0.825,
     212,
     506,
     718,
     359,
     61,
     55,
     171,
     214,
     1221],
    [203999,
     '2017-18',
     '00',
     1610612743,
     'DEN',
     23.0,
     75,
     73,
     2443.0,
     504,
     1010,
     0.499,
     111,
     280,
     0.396,
     266,
     313,
     0.85,
     195,
     608,
     803,
     458,
     90,
     61,
     210,
     212,
     1385],
    [203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     24.0,
     80,
     80,
     2504.0,
     616,
     1206,
     0.511,
     83,
     270,
     0.307,
     289,
     352,
     0.821,
     228,
     637,
     865,
     580,
     108,
     55,
     248,
     228,
     1604],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     25.0,
     73,
     73,
     2335.0,
     565,
     1071,
     0.528,
     80,
     255,
     0.314,
     246,
     301,
     0.817,
     166,
     545,
     711,
     512,
     85,
     44,
     226,
     222,
     1456],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     26.0,
     72,
     72,
     2488.0,
     732,
     1293,
     0.566,
     92,
     237,
     0.388,
     342,
     394,
     0.868,
     205,
     575,
     780,
     599,
     95,
     48,
     222,
     192,
     1898],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     27.0,
     74,
     74,
     2476.0,
     764,
     1311,
     0.583,
     97,
     288,
     0.337,
     379,
     468,
     0.81,
     206,
     813,
     1019,
     584,
     109,
     63,
     281,
     191,
     2004],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     28.0,
     54,
     54,
     1818.0,
     509,
     804,
     0.633,
     45,
     113,
     0.398,
     277,
     336,
     0.824,
     123,
     509,
     632,
     541,
     70,
     36,
     192,
     140,
     1340]]},
  {'name': 'CareerTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     581,
     540,
     17833.0,
     4491,
     8149,
     0.55111,
     581,
     1666,
     0.348739,
     2141,
     2582,
     0.829202,
     1516,
     4572,
     6088,
     3822,
     697,
     412,
     1654,
     1607,
     11704]]},
  {'name': 'SeasonTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     24.0,
     14,
     14,
     556.0,
     132,
     261,
     0.506,
     22,
     56,
     0.393,
     66,
     78,
     0.846,
     54,
     128,
     182,
     118,
     16,
     13,
     36,
     54,
     352],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     25.0,
     19,
     19,
     694.0,
     178,
     343,
     0.519,
     42,
     98,
     0.429,
     66,
     79,
     0.835,
     37,
     150,
     187,
     109,
     20,
     15,
     62,
     68,
     464],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     26.0,
     10,
     10,
     345.0,
     116,
     228,
     0.509,
     20,
     53,
     0.377,
     46,
     55,
     0.836,
     37,
     79,
     116,
     50,
     6,
     9,
     24,
     23,
     298],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     27.0,
     5,
     5,
     171.0,
     61,
     106,
     0.575,
     5,
     18,
     0.278,
     28,
     33,
     0.848,
     17,
     49,
     66,
     29,
     8,
     5,
     24,
     20,
     155]]},
  {'name': 'CareerTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     48,
     48,
     1767.0,
     487,
     938,
     0.519189,
     89,
     225,
     0.395555,
     206,
     245,
     0.840816,
     145,
     406,
     551,
     306,
     50,
     42,
     146,
     165,
     1269]]},
  {'name': 'SeasonTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610616833,
     'GNS',
     24.0,
     1,
     0,
     13.0,
     3,
     4,
     0.75,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     3,
     6,
     9,
     0,
     0,
     0,
     1,
     1,
     6],
    [203999,
     '2019-20',
     '00',
     1610616834,
     'LBN',
     25.0,
     1,
     0,
     12.0,
     2,
     4,
     0.5,
     1,
     3,
     0.333,
     0,
     0,
     0.0,
     0,
     2,
     2,
     1,
     1,
     0,
     0,
     1,
     5],
    [203999,
     '2020-21',
     '00',
     1610616834,
     'LBN',
     26.0,
     1,
     1,
     19.0,
     3,
     4,
     0.75,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     0,
     7,
     7,
     5,
     0,
     1,
     2,
     1,
     6],
    [203999,
     '2021-22',
     '00',
     1610616834,
     'LBN',
     27.0,
     1,
     1,
     21.0,
     4,
     5,
     0.8,
     2,
     3,
     0.667,
     0,
     0,
     0.0,
     3,
     6,
     9,
     8,
     1,
     0,
     1,
     0,
     10],
    [203999,
     '2022-23',
     '00',
     1610616834,
     'LBN',
     28.0,
     1,
     1,
     20.0,
     2,
     4,
     0.5,
     0,
     1,
     0.0,
     0,
     0,
     0.0,
     3,
     2,
     5,
     6,
     2,
     0,
     2,
     0,
     4]]},
  {'name': 'CareerTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     5,
     3,
     86.0,
     14,
     21,
     0.666666,
     3,
     7,
     0.428571,
     0,
     0,
     0.0,
     9,
     23,
     32,
     20,
     4,
     1,
     6,
     3,
     31]]},
  {'name': 'SeasonTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'SCHOOL_NAME',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonRankingsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[203999,
     '2015-16',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     152,
     112,
     135,
     18,
     223,
     227,
     None,
     90,
     104,
     58,
     24,
     45,
     38,
     82,
     61,
     68,
     115,
     120,
     50],
    [203999,
     '2016-17',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     108,
     34,
     68,
     6,
     192,
     188,
     None,
     61,
     65,
     46,
     12,
     17,
     13,
     31,
     106,
     51,
     32,
     41,
     17],
    [203999,
     '2017-18',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     40,
     29,
     36,
     29,
     88,
     99,
     35,
     25,
     30,
     26,
     10,
     8,
     7,
     12,
     38,
     47,
     16,
     26,
     8],
    [203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     34,
     19,
     25,
     31,
     128,
     107,
     128,
     28,
     34,
     52,
     10,
     9,
     8,
     6,
     19,
     53,
     9,
     22,
     4],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     11,
     11,
     21,
     19,
     127,
     102,
     142,
     29,
     30,
     56,
     14,
     8,
     8,
     6,
     25,
     63,
     8,
     18,
     3],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     3,
     1,
     8,
     14,
     117,
     132,
     75,
     12,
     14,
     26,
     8,
     7,
     5,
     3,
     11,
     55,
     5,
     3,
     1],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     18,
     2,
     8,
     8,
     121,
     110,
     120,
     9,
     8,
     63,
     13,
     1,
     1,
     6,
     10,
     34,
     5,
     5,
     1],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     47,
     10,
     42,
     7,
     189,
     218,
     None,
     18,
     19,
     59,
     28,
     4,
     4,
     2,
     19,
     65,
     5,
     18,
     1]]},
  {'name': 'SeasonRankingsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     13,
     7,
     9,
     14,
     20,
     28,
     29,
     8,
     10,
     27,
     1,
     6,
     4,
     4,
     18,
     14,
     12,
     10,
     4],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     6,
     4,
     4,
     12,
     10,
     16,
     19,
     10,
     10,
     31,
     4,
     2,
     4,
     4,
     11,
     8,
     2,
     5,
     3],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     37,
     13,
     13,
     18,
     36,
     38,
     44,
     14,
     15,
     30,
     8,
     16,
     12,
     20,
     58,
     25,
     19,
     14,
     13],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     85,
     32,
     44,
     7,
     97,
     90,
     79,
     32,
     34,
     21,
     26,
     38,
     35,
     44,
     51,
     53,
     27,
     38,
     37]]}]}

In [7]:
#Jokic players stats
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,54,54,1818.0,509,...,0.824,123,509,632,541,70,36,192,140,1340

In [9]:
career.get_data_frames()[1]

,PLAYER_ID,LEAGUE_ID,Team_ID,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,00,0,581,540,17833.0,4491,8149,0.55111,581,...,0.829202,1516,4572,6088,3822,697,412,1654,1607,11704

In [13]:
df = career.get_data_frames()
type(df[1])

pandas.core.frame.DataFrame

In [20]:
df[0]
# scatter plot
df.plot(kind = 'scatter',
        x = 'SEASON_ID',
        y = 'PTS',
        color = 'red')

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,54,54,1818.0,509,...,0.824,123,509,632,541,70,36,192,140,1340